# Build and deploy static website

trigger:
  branches:
   include:
     - master
  paths:
    include:
      - website/*


variables:
  skipComponentGovernanceDetection: true
  westEuropeStorageAccount: mattwhiteblogwesteurope
  northEuropeStorageAccount: mattwhiteblognortheurope
  azureSubscription: mattwhiteazuresub
  sasTokenTimeoutInMinutes: 30
  azStorageBlobDeleteBatchCommand: az storage blob delete-batch --source '$web' --account-name

stages:
- stage: Build
  displayName: Build website using Hugo
  variables:
    dockerVersion: 19.03.1
    containerImage: klakegg/hugo
  jobs:
  - job: containerbuild
    displayName: Build website using Docker container
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: $(dockerVersion)
        releaseType: stable
    - task: Docker@2
      displayName: Docker login
      inputs:
        command: login
        containerRegistry: dockerhub
    - script: |
        export HUGO_VERSION=`cat HUGO_VERSION`
        docker pull $CONTAINER_IMAGE:$HUGO_VERSION-ext
      env:
        CONTAINER_IMAGE: $(containerImage)
      displayName: Docker pull
      workingDirectory: $(Build.Repository.LocalPath)/website
    - script: |
        export HUGO_VERSION=`cat HUGO_VERSION`
        docker run --rm \
                   --interactive \
                   --user $UID:$UID \
                   --volume $PWD:/src \
                   --volume $(Build.ArtifactStagingDirectory):/target \
                   klakegg/hugo:$HUGO_VERSION-ext
      displayName: Docker run (build site)
      workingDirectory: $(Build.Repository.LocalPath)/website
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifact: website

- stage: deploy
  displayName: Deploy website to Azure Storage
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: westeuropecopy
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: none
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(azureSubscription)
        scriptLocation: inlineScript
        inlineScript: $(azStorageBlobDeleteBatchCommand) $(westEuropeStorageAccount)
        failOnStandardError: true
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: website
        buildType: current
        targetPath: $(Pipeline.Workspace)/website
    - task: AzureFileCopy@3
      inputs:
        sourcePath: $(Pipeline.Workspace)/website
        azureSubscription: $(azureSubscription)
        destination: azureBlob
        storage: $(westEuropeStorageAccount)
        containerName: '$web'
        sasTokenTimeOutInMinutes: $(sasTokenTimeoutInMinutes)

  - job: northeuropecopy
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: none
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(azureSubscription)
        scriptLocation: inlineScript
        inlineScript: $(azStorageBlobDeleteBatchCommand) $(northEuropeStorageAccount)
        failOnStandardError: true
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: website
        buildType: current
        targetPath: $(Pipeline.Workspace)/website
    - task: AzureFileCopy@3
      inputs:
        sourcePath: $(Pipeline.Workspace)/website
        azureSubscription: $(azureSubscription)
        destination: azureBlob
        storage: $(northEuropeStorageAccount)
        containerName: '$web'
        sasTokenTimeOutInMinutes: $(sasTokenTimeoutInMinutes)