# Build and deploy static website

trigger:
- master
- azure-pipelines-dev

variables:
  skipComponentGovernanceDetection: true
  westEuropeStorageAccount: mattwhiteblogwesteurope
  northEuropeStorageAccount: mattwhiteblognortheurope
  azureSubscription: mattwhiteazuresub
  sasTokenTimeoutInMinutes: 30

stages:
- stage: Build
  displayName: Build website using Hugo
  variables:
    dockerVersion: 19.03.1
  jobs:
  - job: containerbuild
    displayName: Build website using Docker container
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: $(dockerVersion)
        releaseType: stable
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: dockerhub
    - script: |
        export HUGO_VERSION=`cat HUGO_VERSION`
        docker pull klakegg/hugo:$HUGO_VERSION-ext
      displayName: Docker pull
      workingDirectory: $(Build.Repository.LocalPath)/website
    - script: |
        export HUGO_VERSION=`cat HUGO_VERSION`
        docker run --rm --interactive --user $UID:$UID --volume .:/src --volume ./build:/target klakegg/hugo:$HUGO_VERSION-ext
      displayName: Docker run (build site)
      workingDirectory: $(Build.Repository.LocalPath)/website
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.Repository.LocalPath)/website
        artifact: website

- stage: deploy
  displayName: Deploy website to Azure Storage
  dependsOn: Build
  condition: ${{ False }}
  jobs:
  - job: westeuropecopy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureFileCopy@3
      inputs:
        sourcePath: $(Build.Repository.LocalPath)
        azureSubscription: $(azureSubscription)
        destination: azureBlob
        storage: $(westEuropeStorageAccount)
        containerName: '$web'
        sasTokenTimeOutInMinutes: 30

  - job: northeuropecopy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureFileCopy@3
      inputs:
        sourcePath: $(Build.Repository.LocalPath)
        azureSubscription: $(azureSubscription)
        destination: azureBlob
        storage: $(northEuropeStorageAccount)
        containerName: '$web'
        sasTokenTimeOutInMinutes: 30