baseURL: 'https://mattwhite.blog'
title: Matt White's Blog
theme: hugo-theme-den
enableEmoji: true
enableRobotsTXT: true
hasCJKLanguage: false
preserveTaxonomyNames: true
rssLimit: 20
paginate: 20
paginatePath: page
PygmentsCodeFences: true
PygmentsUseClasses: true
disqusShortname: mattwhiteblog
googleAnalytics: 'UA-148159929-1'
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
permalinks:
  posts: '/:year/:month/:slug/'
  categories: '/category/:slug/'
  tags: '/tag/:slug/'
  pages: '/:slug/'
author:
  name: Matt White
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  since: '2019'
  rssFullContent: false
  keywords:
    - Azure
    - blog
    - hugo
    - devops
    - git
  description: >-
    Adventures in Azure
  logoTitle: Home
  #siteLogoImage: 
  headerImage: images/blog-header.jpg
  showAuthorCard: true
  showMenuLanguages: false
  autoLoadComments: false
  dateFormatToUse: '2006-01-02'
  google_verification: ''
  customCSS: []
  customJS: []
taxonomies:
  category: categories
  tag: tags
  series: series
  keyword: keywords
related:
  threshold: 50
  includeNewer: true
  toLower: false
  indices:
    - name: categories
      weight: 200
    - name: keywords
      weight: 150
    - name: tags
      weight: 100
    - name: series
      weight: 75
languages:
  en:
    languageCode: en
    languageName: English
    #contentDir: content/
    weight: 1
    menu:
      main:
        - name: About Me
          weight: 10
          identifier: aboutme
          url: /about
      social:
        - name: GitHub
          weight: 10
          identifier: github
          url: 'https://github.com/matt-FFFFFF'
          pre: '<a href="https://github.com/matt-FFFFFF" target="_blank"><i class="fab fa-github"></i></a>&nbsp'
        - name: 'Twitter'
          weight: 20
          identifier: twitter
          url: https://twitter.com/matthewwhite
          pre: '<a href="https://twitter.com/matthewwhite" target="_blank"><i class="fab fa-twitter"></i></a>&nbsp'
        - name: 'LinkedIn'
          weight: 10
          identifier: linkedin
          url: 'https://www.linkedin.com/in/whitematthew'
          pre: '<a href="https://www.linkedin.com/in/whitematthew" target="_blank"><i class="fab fa-linkedin"></i></a>&nbsp'
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true