baseURL: 'https://mattwhite.blog'
title: Matt White's Blog
theme: hugo-theme-den
enableEmoji: true
enableRobotsTXT: true
hasCJKLanguage: false
preserveTaxonomyNames: true
rssLimit: 20
paginate: 20
paginatePath: page
PygmentsCodeFences: true
PygmentsUseClasses: true
disqusShortname: mattwhiteblog
googleAnalytics: 'UA-148159929-1'
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
permalinks:
  posts: '/:year/:month/:slug/'
  categories: '/category/:slug/'
  tags: '/tag/:slug/'
  pages: '/:slug/'
author:
  name: Matt White
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  since: '2019'
  rssFullContent: true
  keywords:
    - Azure
    - blog
    - hugo
    - devops
    - git
  description: >-
    Adventures in Azure
  logoTitle: Home
  #siteLogoImage: images/globe.svg
  headerImage: images/blog-header.jpg
  showAuthorCard: true
  showMenuLanguages: false
  autoLoadComments: false
  dateFormatToUse: '2006-01-02'
  google_verification: ''
  customCSS: []
  customJS: []
taxonomies:
  category: categories
  tag: tags
  series: series
  keyword: keywords
related:
  threshold: 50
  includeNewer: true
  toLower: false
  indices:
    - name: categories
      weight: 200
    - name: keywords
      weight: 150
    - name: tags
      weight: 100
    - name: series
      weight: 75
languages:
  en:
    languageCode: en
    languageName: English
    #contentDir: content/
    weight: 1
    menu:
      main:
        - name: About Me
          weight: 10
          identifier: aboutme
          url: /about
      social:
        - name: GitHub
          weight: 10
          identifier: github
          url: 'https://github.com/matt-FFFFFF/'
        - name: 'Twitter'
          weight: 20
          identifier: twitter
          url: https://twitter.com/matthewwhite
        - name: 'LinkedIn'
          weight: 10
          identifier: linkedin
          url: 'https://www.linkedin.com/in/whitematthew'
#      links:
#        - name: About Me
#          weight: 10
#          identifier: about_me
#          url: /about